// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitterTimeLineFilterEF.Models;

namespace TwitterTimeLineFilterEF.Migrations
{
    [DbContext(typeof(UserTagContext))]
    [Migration("20211113124115_Datetime")]
    partial class Datetime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("TwitterTimeLineFilterEF.Models.Tweet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Html")
                        .HasColumnType("TEXT");

                    b.Property<long>("TweetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TwitterUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TwitterUserId");

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("TwitterTimeLineFilterEF.Models.TwitterUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("TwitterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TwitterUsers");
                });

            modelBuilder.Entity("TwitterTimeLineFilterEF.Models.UserTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserTags");
                });

            modelBuilder.Entity("TwitterUserUserTag", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TwitterUserUserTag");
                });

            modelBuilder.Entity("TwitterTimeLineFilterEF.Models.Tweet", b =>
                {
                    b.HasOne("TwitterTimeLineFilterEF.Models.TwitterUser", "TwitterUser")
                        .WithMany("Tweets")
                        .HasForeignKey("TwitterUserId");

                    b.Navigation("TwitterUser");
                });

            modelBuilder.Entity("TwitterUserUserTag", b =>
                {
                    b.HasOne("TwitterTimeLineFilterEF.Models.UserTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitterTimeLineFilterEF.Models.TwitterUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TwitterTimeLineFilterEF.Models.TwitterUser", b =>
                {
                    b.Navigation("Tweets");
                });
#pragma warning restore 612, 618
        }
    }
}
